name: Ejecutar Predictor de Apuestas

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */12 * * *' # Se ejecuta automáticamente cada 12 horas
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests

      - name: Correr Predictor
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python main.py
